services:
  - type: web
    plan: free
    name: expense-tracker-web
    runtime: python
    buildCommand: "cd expense_tracker && pip install -r ../requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input"
    startCommand: "cd expense_tracker && gunicorn --pythonpath . expense_tracker.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: expense_tracker.settings
