services:
  - type: web
    plan: free
    name: expense-tracker-web
    runtime: python
    buildCommand: "pip install -r requirements.txt && cd expense_tracker && python manage.py migrate && python manage.py collectstatic --no-input"
    startCommand: "gunicorn --chdir expense_tracker expense_tracker.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: expense_tracker.settings
